import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { rankUpdates, LIMITS, parseStrictJson } from '../src/index.mjs';

const dep = (name='sample', version='1.0.0') => ({ name, version });
const factor = (name='sample', usage='low', directUse=true, rollback='ready') => ({ name, usage, directUse, rollback });
const advisory = (name='sample', severity='none') => ({ name, severity });
const note = (name='sample', breaking=false) => ({ name, breaking });
const doc = (before=[dep()], after=[dep('sample','1.0.1')], factors=[factor()], advisories=[advisory()], apiNotes=[note()]) => ({ schemaVersion:'1', complete:true, before:{complete:true,dependencies:before}, after:{complete:true,dependencies:after}, factors:{complete:true,items:factors}, advisories:{complete:true,items:advisories}, apiNotes:{complete:true,items:apiNotes} });
const run = (root,input) => spawnSync(process.execPath,['bin/dependency-update-risk-map.mjs','--root',root,'--input',input],{cwd:new URL('..',import.meta.url),encoding:'utf8',env:{...process.env,NODE_OPTIONS:'--import=/Users/km/Desktop/web/open-source/migration-plan-template/support/deny-network.mjs'}});

test('a fully evidenced low-risk patch is ranked and passes',()=>{const r=rankUpdates(doc());assert.equal(r.status,'pass');assert.equal(r.summary.checked,1);assert.equal(r.rankedUpdates[0].kind,'patch');assert.equal(r.rankedUpdates[0].score,4);assert.deepEqual(r.findings,[])});
test('heavily used major outranks unused patch under same policy',()=>{
  const r=rankUpdates(doc([dep('heavy','1.0.0'),dep('idle','1.0.0')],[dep('heavy','2.0.0'),dep('idle','1.0.1')],[factor('heavy','high',true,'ready'),factor('idle','none',false,'ready')],[advisory('heavy'),advisory('idle')],[note('heavy'),note('idle')]));
  assert.equal(r.rankedUpdates[0].kind,'major');assert.ok(r.rankedUpdates[0].score>r.rankedUpdates[1].score);assert.equal(r.status,'fail');assert.ok(!JSON.stringify(r).includes('heavy'));
});
test('breaking API and absent rollback increase transparent score',()=>{const r=rankUpdates(doc(undefined,undefined,[factor('sample','low',true,'none')],undefined,[note('sample',true)]));assert.equal(r.status,'fail');assert.ok(r.rankedUpdates[0].factors.some(f=>f.name==='breaking-api'))});
test('missing advisory or API notes are explicitly unknown, not low-risk pass',()=>{const a=rankUpdates(doc(undefined,undefined,undefined,[],undefined));assert.equal(a.status,'incomplete');assert.equal(a.findings[0].ruleId,'advisory-missing');const n=rankUpdates(doc(undefined,undefined,undefined,undefined,[]));assert.equal(n.status,'incomplete');assert.equal(n.findings[0].ruleId,'api-note-missing')});
test('added and removed dependencies are ranked; empty update set incomplete',()=>{const r=rankUpdates(doc([dep('old')],[dep('new')],[factor('old'),factor('new')],[advisory('old'),advisory('new')],[note('old'),note('new')]));assert.equal(r.rankedUpdates.length,2);assert.equal(rankUpdates(doc([dep()],[dep()],[],[],[])).status,'incomplete')});
test('invalid, duplicate or partial evidence never passes',()=>{const x=doc();x.advisories.complete=false;assert.equal(rankUpdates(x).status,'incomplete');assert.equal(rankUpdates(doc([dep(),dep()])).status,'incomplete');assert.equal(rankUpdates(doc(undefined,undefined,[{...factor(),usage:'maybe'}])).status,'incomplete')});
test('each collection bound accepts N, rejects N+1',()=>{const deps=Array.from({length:LIMITS.records},(_,i)=>dep(`p${i}`,'1.0.0'));const next=deps.map(x=>({...x,version:'1.0.1'}));const factors=deps.map(x=>factor(x.name));const advisories=deps.map(x=>advisory(x.name));const apiNotes=deps.map(x=>note(x.name));const x=doc(deps,next,factors,advisories,apiNotes);assert.equal(rankUpdates(x).status,'pass');for(const key of ['before','after','factors','advisories','apiNotes']){const y=structuredClone(x);const arr=key==='before'||key==='after'?y[key].dependencies:y[key].items;arr.push(key==='before'||key==='after'?dep('extra'):key==='factors'?factor('extra'):key==='advisories'?advisory('extra'):note('extra'));assert.equal(rankUpdates(y).findings[0].ruleId,'record-limit')}});
test('byte, depth and injected time exact N pass, N+1 incomplete',()=>{const x=doc();x.factors.items[0].note='';const overhead=Buffer.byteLength(JSON.stringify(x));x.factors.items[0].note='x'.repeat(LIMITS.bytes-overhead);assert.equal(rankUpdates(x).status,'pass');x.factors.items[0].note+='x';assert.equal(rankUpdates(x).findings[0].ruleId,'byte-limit');const deep=doc();assert.equal(rankUpdates(deep).status,'pass');deep.factors.items[0].note={nested:'x'};assert.equal(rankUpdates(deep).findings[0].ruleId,'depth-limit');assert.equal(rankUpdates(doc(),{now:(()=>{let n=0;return()=>n++?LIMITS.milliseconds:0})()}).status,'pass');assert.equal(rankUpdates(doc(),{now:(()=>{let n=0;return()=>n++?LIMITS.milliseconds+1:0})()}).findings[0].ruleId,'time-limit')});
test('duplicate JSON keys including escaped spelling are refused',()=>assert.throws(()=>parseStrictJson('{"complete":false,"complet\\u0065":true}'),/duplicate-key/));
test('CLI strict UTF-8, realpath confinement and empty usage stdout',async()=>{const root=await mkdtemp(join(tmpdir(),'risk-'));await writeFile(join(root,'good.json'),JSON.stringify(doc()));assert.equal(run(root,'good.json').status,0);await writeFile(join(root,'bad.json'),Buffer.from([0xff]));assert.equal(JSON.parse(run(root,'bad.json').stdout).status,'incomplete');await symlink(tmpdir(),join(root,'escape'));const escaped=run(root,'escape/nonexistent.json');assert.equal(escaped.status,2);assert.equal(JSON.parse(escaped.stdout).status,'incomplete');const usage=spawnSync(process.execPath,['bin/dependency-update-risk-map.mjs','--root',root,'--input','good.json','--unknown'],{cwd:new URL('..',import.meta.url),encoding:'utf8'});assert.equal(usage.status,2);assert.equal(usage.stdout,'')});
